server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp
dubbo:
  scan:
    basePackages: com.jt  #包扫描路径
  application:
    name: consumer-web  #服务名称
  registry:
    address: zookeeper://192.168.79.129:2181?backup=192.168.79.129:2182,192.168.79.129:2183

  